title: "./my-blog"
description: "Mere thoughts, code, aur kuch aur"
author: "Zainab Aamir"
email: "aap@example.com"
url: "https://github.com/Zainab937/laattmpt.github.io"
baseurl: "/laatmpt"

twitter_username: aapka_twitter
github_username: aapka_github

plugins:
  - jekyll-feed
  - jekyll-sitemap

permalink: /:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
